'use client';

import { useRef, useEffect, useState } from 'react';
import Link from 'next/link';
import { motion, useInView } from 'framer-motion';
import Navigation from '@/components/layout/Navigation';
import Footer from '@/components/layout/Footer';

/* ============================================================
   Types
   ============================================================ */
interface CommitmentSection {
  title: string;
  subtitle: string;
  body: string[];
  dark: boolean;
  gradientFrom: string;
  gradientTo: string;
  tag: string;
}

interface FarmerProfile {
  name: string;
  location: string;
  tenure: string;
  quote: string;
  detail: string;
  initial: string;
}

interface ImpactStat {
  value: number;
  suffix: string;
  label: string;
  description: string;
}

interface Certification {
  name: string;
  body: string;
  icon: string;
}

/* ============================================================
   Data
   ============================================================ */
const COMMITMENTS: CommitmentSection[] = [
  {
    tag: 'Commitment 01',
    title: 'Ethical Sourcing',
    subtitle: 'Fair value, from farm to cup',
    body: [
      'Every kilogram of HIMA BEANS coffee carries a fair-trade premium that goes directly to the farming families who grow it. We pay above the international market rate — not as charity, but as a recognition of the exceptional craft and terroir these farmers steward.',
      'Our direct-relationship model means no exploitative middlemen, no opaque pricing, and no negotiating farmers into poverty. We sit at the table together, negotiate transparently, and sign multi-year agreements that give communities the stability to invest in their own futures.',
      'For us, ethical sourcing isn\'t a certification — it\'s the foundation of every business decision we make.',
    ],
    dark: true,
    gradientFrom: '#182118',
    gradientTo: '#5C3D2E',
  },
  {
    tag: 'Commitment 02',
    title: 'Shade Grown',
    subtitle: 'Coffee in its natural home',
    body: [
      'All HIMA BEANS coffee is grown beneath the canopy of native Himalayan trees. This traditional shade-growing practice isn\'t an add-on to our sourcing — it is the source of our coffee\'s character.',
      'Shade-grown cultivation slows the ripening of coffee cherries, concentrating sugars and aromatic compounds that create the floral, complex cup we\'re known for. It also maintains critical biodiversity corridors for over 60 migratory bird species that pass through Nepal\'s highland forests each season.',
      'By refusing to clear-cut for sun-cultivation monocultures, our farming partners preserve the living ecosystem that makes Himalayan coffee possible — for this generation and the next.',
    ],
    dark: false,
    gradientFrom: '#6E675F',
    gradientTo: '#A89D8E',
  },
  {
    tag: 'Commitment 03',
    title: 'Traceable Supply Chain',
    subtitle: 'Know every farmer, every farm',
    body: [
      'When you buy a bag of HIMA BEANS, you\'re not buying a commodity blend. Every batch is traceable to a specific farmer, cooperative, and district in Nepal. We publish full origin data — GPS coordinates, farmer profiles, harvest dates, and processing method — for every lot we sell.',
      'Our farm-to-roaster traceability system was built in partnership with Nepali cooperative leaders to ensure data sovereignty: farmers control their own story, and we share it with your permission and theirs.',
      'This isn\'t just transparency for marketing. It\'s accountability — a record of every hand that touched your coffee, and a guarantee that each one was paid fairly.',
    ],
    dark: true,
    gradientFrom: '#1A1814',
    gradientTo: '#182118',
  },
  {
    tag: 'Commitment 04',
    title: 'Sustainable Shipping',
    subtitle: 'Minimal footprint, maximum care',
    body: [
      'We offset 100% of the carbon generated by shipping through our partnership with certified reforestation projects in the Terai lowlands — the same region where Nepal\'s coffee culture was born.',
      'Our packaging uses recycled kraft board, soy-based inks, and a resealable valve bag with the smallest possible plastic footprint. We\'re actively trialling fully home-compostable pouches for 2025 release.',
      'We ship in consolidated freight runs to reduce per-kilo emissions, and we\'re working with our logistics partner on a sea-freight-first model for wholesale customers — cutting air-freight emissions by up to 90% on each pallet.',
    ],
    dark: false,
    gradientFrom: '#7B5920',
    gradientTo: '#6E675F',
  },
];

const FARMERS: FarmerProfile[] = [
  {
    name: 'Rama Gurung',
    location: 'Gulmi District, Gandaki Province',
    tenure: '15 years of specialty farming',
    quote:
      '"My grandfather planted these trees. I learned to read the cherries from my mother. Now my daughter is learning too. HIMA BEANS gives us the reason to keep going."',
    detail:
      'Rama grows on a 2.4-hectare farm at 2,100 metres. She leads a 22-member women\'s cooperative that has increased collective income by 38% since joining our direct-trade programme in 2021. Her lots are prized for exceptional jasmine florals.',
    initial: 'RG',
  },
  {
    name: 'Sita Thapa',
    location: 'Palpa District, Lumbini Province',
    tenure: '3rd generation coffee farmer',
    quote:
      '"My grandmother didn\'t know her coffee would one day be served in Australia. I think she would have laughed — and then she would have made you the best cup you\'ve ever had."',
    detail:
      'Sita manages the Thapa family farm that has been shade-growing coffee for over 70 years. As a third-generation farmer, she has pioneered wet-processing techniques in Palpa that produce the region\'s cleanest, most consistently high-scoring lots.',
    initial: 'ST',
  },
];

const IMPACT_STATS: ImpactStat[] = [
  {
    value: 150,
    suffix: '+',
    label: 'Farmers Supported',
    description: 'Direct-trade relationships across Nepal',
  },
  {
    value: 2000,
    suffix: 'kg',
    label: 'Avg. Fair-Trade Premium',
    description: 'Above market rate paid per season',
  },
  {
    value: 85,
    suffix: '%',
    label: 'Women-Led Cooperatives',
    description: 'Of our partner farming groups',
  },
  {
    value: 0,
    suffix: '',
    label: 'Forced Labour',
    description: 'Zero tolerance across our entire supply chain',
  },
];

const CERTIFICATIONS: Certification[] = [
  {
    name: 'Fair Trade Certified',
    body: 'Fair Trade International',
    icon: '⊕',
  },
  {
    name: 'Rainforest Alliance',
    body: 'Rainforest Alliance Inc.',
    icon: '◈',
  },
  {
    name: 'Organic',
    body: 'NASAA Certified Organic',
    icon: '◎',
  },
  {
    name: 'B Corporation',
    body: 'B Lab Australia',
    icon: '◆',
  },
];

/* ============================================================
   Animated Counter
   ============================================================ */
function AnimatedCounter({
  value,
  suffix,
  duration = 1.8,
}: {
  value: number;
  suffix: string;
  duration?: number;
}) {
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: '-60px' });
  const [display, setDisplay] = useState(0);

  useEffect(() => {
    if (!inView) return;
    if (value === 0) {
      setDisplay(0);
      return;
    }
    const startTime = performance.now();
    const endValue = value;

    function tick(now: number) {
      const elapsed = now - startTime;
      const progress = Math.min(elapsed / (duration * 1000), 1);
      // Ease out quart
      const eased = 1 - Math.pow(1 - progress, 4);
      setDisplay(Math.round(eased * endValue));
      if (progress < 1) requestAnimationFrame(tick);
    }

    requestAnimationFrame(tick);
  }, [inView, value, duration]);

  return (
    <span ref={ref} className="tabular-nums">
      {display}
      {suffix}
    </span>
  );
}

/* ============================================================
   Sub-components
   ============================================================ */

function CommitmentBlock({
  section,
  index,
}: {
  section: CommitmentSection;
  index: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-80px' });
  const isEven = index % 2 === 0;

  return (
    <section
      style={{
        backgroundColor: section.dark ? '#1A1814' : '#F3EFE6',
      }}
    >
      <div
        ref={ref}
        className={`site-container py-14 md:py-20 lg:py-24 grid lg:grid-cols-2 gap-10 lg:gap-20 items-center ${
          !isEven ? 'lg:grid-flow-dense' : ''
        }`}
      >
        {/* Image placeholder */}
        <motion.div
          initial={{ opacity: 0, x: isEven ? -40 : 40 }}
          animate={inView ? { opacity: 1, x: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.25, 1, 0.5, 1] as [number,number,number,number] }}
          className={`rounded-3xl overflow-hidden aspect-[4/3] ${!isEven ? 'lg:col-start-2' : ''}`}
          style={{
            background: `linear-gradient(135deg, ${section.gradientFrom} 0%, ${section.gradientTo} 100%)`,
          }}
        >
          <div className="w-full h-full flex items-center justify-center">
            <span
              className="font-serif text-7xl opacity-20 select-none"
              style={{ color: '#F3EFE6' }}
            >
              {index + 1 < 10 ? `0${index + 1}` : index + 1}
            </span>
          </div>
        </motion.div>

        {/* Text */}
        <motion.div
          initial={{ opacity: 0, x: isEven ? 40 : -40 }}
          animate={inView ? { opacity: 1, x: 0 } : {}}
          transition={{ duration: 0.8, delay: 0.1, ease: [0.25, 1, 0.5, 1] as [number,number,number,number] }}
          className={!isEven ? 'lg:col-start-1 lg:row-start-1' : ''}
        >
          <p
            className="font-sans text-xs font-semibold tracking-[0.2em] uppercase mb-3"
            style={{ color: '#7B5920' }}
          >
            {section.tag}
          </p>
          <h2
            className="font-serif text-4xl md:text-5xl font-bold leading-tight mb-3"
            style={{ color: section.dark ? '#F3EFE6' : '#182118' }}
          >
            {section.title}
          </h2>
          <p
            className="font-serif text-xl italic mb-8"
            style={{ color: '#7B5920' }}
          >
            {section.subtitle}
          </p>
          <div className="space-y-4">
            {section.body.map((para, i) => (
              <p
                key={i}
                className="font-sans text-base leading-relaxed"
                style={{ color: section.dark ? '#EDE6D8' : '#6E675F' }}
              >
                {para}
              </p>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  );
}

function FarmerCard({ farmer, index }: { farmer: FarmerProfile; index: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-60px' });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 40 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.7, delay: index * 0.15, ease: [0.25, 1, 0.5, 1] as [number,number,number,number] }}
      className="bg-white rounded-3xl overflow-hidden border border-[#EDE6D8]"
    >
      {/* Avatar banner */}
      <div
        className="h-32 flex items-end px-8 pb-0 relative"
        style={{
          background: 'linear-gradient(135deg, #182118 0%, #7B5920 100%)',
        }}
      >
        <div
          className="w-20 h-20 rounded-full border-4 border-white flex items-center justify-center translate-y-10 font-serif text-xl font-bold"
          style={{ backgroundColor: '#7B5920', color: '#F3EFE6' }}
        >
          {farmer.initial}
        </div>
      </div>

      <div className="px-8 pt-14 pb-8">
        <h3 className="font-serif text-2xl text-[#182118] font-semibold mb-1">{farmer.name}</h3>
        <p className="font-sans text-sm text-[#7B5920] font-semibold mb-0.5">{farmer.location}</p>
        <p className="font-sans text-xs text-[#6E675F] mb-6">{farmer.tenure}</p>

        <blockquote className="font-serif text-base italic text-[#182118] leading-relaxed mb-6 border-l-2 border-[#7B5920] pl-4">
          {farmer.quote}
        </blockquote>

        <p className="font-sans text-sm text-[#6E675F] leading-relaxed">{farmer.detail}</p>
      </div>
    </motion.div>
  );
}

function ImpactCard({ stat, index }: { stat: ImpactStat; index: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-60px' });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 30 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay: index * 0.1, ease: [0.25, 1, 0.5, 1] as [number,number,number,number] }}
      className="text-center px-4 sm:px-6 py-6 sm:py-8"
    >
      <div className="font-serif text-4xl md:text-5xl lg:text-6xl font-bold text-[#7B5920] mb-2">
        <AnimatedCounter value={stat.value} suffix={stat.suffix} />
      </div>
      <p className="font-serif text-xl text-[#F3EFE6] font-semibold mb-2">{stat.label}</p>
      <p className="font-sans text-sm text-[#6E675F]">{stat.description}</p>
    </motion.div>
  );
}

function CertBadge({ cert, index }: { cert: Certification; index: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-40px' });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, scale: 0.85 }}
      animate={inView ? { opacity: 1, scale: 1 } : {}}
      transition={{ duration: 0.5, delay: index * 0.1, ease: [0.25, 1, 0.5, 1] as [number,number,number,number] }}
      className="flex flex-col items-center gap-3 p-8 rounded-2xl border-2 border-[#EDE6D8] bg-white"
    >
      <div
        className="w-16 h-16 rounded-full flex items-center justify-center text-2xl"
        style={{ backgroundColor: '#F3EFE6', color: '#7B5920' }}
      >
        {cert.icon}
      </div>
      <p className="font-serif text-lg text-[#182118] font-semibold text-center">{cert.name}</p>
      <p className="font-sans text-xs text-[#6E675F] text-center">{cert.body}</p>
    </motion.div>
  );
}

/* ============================================================
   Page
   ============================================================ */
export default function SustainabilityPage() {
  const heroRef = useRef<HTMLDivElement>(null);
  const heroInView = useInView(heroRef, { once: true });

  return (
    <>
      <Navigation />
      <main className="min-h-screen" style={{ backgroundColor: '#F3EFE6' }}>
      {/* ── Hero ── */}
      <section
        ref={heroRef}
        className="relative min-h-[70vh] md:min-h-[80vh] flex items-end pb-16 md:pb-24 overflow-hidden"
        style={{ backgroundColor: '#1A1814' }}
      >
        {/* Mountain gradient */}
        <div
          className="absolute inset-0"
          style={{
            background:
              'radial-gradient(ellipse at 50% 100%, #182118 0%, transparent 60%), radial-gradient(ellipse at 80% 30%, #6E675F 0%, transparent 50%), radial-gradient(ellipse at 20% 60%, #182118 0%, transparent 40%)',
          }}
        />

        {/* Silhouette mountain shape */}
        <div className="absolute bottom-0 inset-x-0 overflow-hidden">
          <svg
            viewBox="0 0 1440 320"
            preserveAspectRatio="none"
            className="w-full h-64 opacity-20"
            fill="#6E675F"
          >
            <path d="M0,320 L0,200 L200,80 L400,180 L600,40 L720,120 L840,20 L1000,140 L1200,60 L1440,160 L1440,320 Z" />
          </svg>
        </div>

        <div className="relative z-10 site-container w-full">
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={heroInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6 }}
            className="font-sans text-[#7B5920] text-sm font-semibold tracking-[0.2em] uppercase mb-6"
          >
            Our Earth Promise
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={heroInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.9, delay: 0.1, ease: [0.25, 1, 0.5, 1] as [number,number,number,number] }}
            className="font-serif text-4xl sm:text-5xl md:text-7xl lg:text-8xl text-[#F3EFE6] font-bold leading-[0.95] mb-6 md:mb-8"
          >
            Our Earth
            <br />
            <em className="text-[#7B5920]">Promise</em>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={heroInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.7, delay: 0.3 }}
            className="font-sans text-[#EDE6D8] text-lg max-w-xl leading-relaxed"
          >
            Every decision we make — from how we source to how we ship — is guided by a single
            commitment: to leave the mountains better than we found them.
          </motion.p>
        </div>
      </section>

      {/* ── Commitment Sections ── */}
      {COMMITMENTS.map((section, index) => (
        <CommitmentBlock key={section.tag} section={section} index={index} />
      ))}

      {/* ── Farmer Stories ── */}
      <section className="py-16 md:py-24" style={{ backgroundColor: '#F3EFE6' }}>
        <div className="site-container">
          <div className="text-center mb-10 md:mb-14">
            <p className="font-sans text-[#7B5920] text-sm font-semibold tracking-[0.2em] uppercase mb-4">
              The People Behind the Cup
            </p>
            <h2 className="font-serif text-3xl md:text-4xl lg:text-5xl text-[#182118] font-bold leading-tight mb-4">
              Farmer Stories
            </h2>
            <p className="font-sans text-[#6E675F] text-base max-w-lg mx-auto leading-relaxed">
              Behind every bag of HIMA BEANS is a farming family with generations of knowledge and a
              story worth knowing.
            </p>
          </div>
          <div className="grid md:grid-cols-2 gap-8">
            {FARMERS.map((farmer, i) => (
              <FarmerCard key={farmer.name} farmer={farmer} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* ── Impact Numbers ── */}
      <section className="py-16 md:py-24" style={{ backgroundColor: '#182118' }}>
        <div className="site-container">
          <div className="text-center mb-10 md:mb-14">
            <p className="font-sans text-[#7B5920] text-sm font-semibold tracking-[0.2em] uppercase mb-4">
              Measured Impact
            </p>
            <h2 className="font-serif text-3xl md:text-4xl lg:text-5xl text-[#F3EFE6] font-bold leading-tight">
              By the Numbers
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 divide-x divide-y divide-[#5C3D2E] border border-[#5C3D2E] rounded-3xl overflow-hidden">
            {IMPACT_STATS.map((stat, i) => (
              <ImpactCard key={stat.label} stat={stat} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* ── Certifications ── */}
      <section className="py-16 md:py-24" style={{ backgroundColor: '#F3EFE6' }}>
        <div className="site-container">
          <div className="text-center mb-10 md:mb-14">
            <p className="font-sans text-[#7B5920] text-sm font-semibold tracking-[0.2em] uppercase mb-4">
              Verified by Third Parties
            </p>
            <h2 className="font-serif text-3xl md:text-4xl lg:text-5xl text-[#182118] font-bold leading-tight mb-4">
              Our Certifications
            </h2>
            <p className="font-sans text-[#6E675F] text-base max-w-lg mx-auto leading-relaxed">
              We hold ourselves accountable through independent verification. These certifications
              reflect the standards we meet — and the higher standards we aim for.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {CERTIFICATIONS.map((cert, i) => (
              <CertBadge key={cert.name} cert={cert} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section
        className="py-16 md:py-24 text-center"
        style={{ backgroundColor: '#182118' }}
      >
        <div className="max-w-2xl mx-auto px-4 sm:px-6">
          <h2 className="font-serif text-3xl md:text-4xl lg:text-5xl text-[#F3EFE6] font-bold leading-tight mb-6">
            Drink Coffee That Does Good
          </h2>
          <p className="font-sans text-[#EDE6D8] text-base leading-relaxed mb-10 opacity-90">
            Every purchase directly supports Nepali farming families and a regenerative supply
            chain. Shop our full bean range and taste the difference ethical sourcing makes.
          </p>
          <div className="flex flex-col sm:flex-row flex-wrap gap-4 justify-center items-center">
            <Link
              href="/beans"
              className="inline-flex items-center justify-center gap-3 w-full sm:w-auto px-8 md:px-10 py-4 rounded-full font-sans font-semibold text-sm tracking-widest uppercase transition-all duration-300 hover:scale-105"
              style={{ backgroundColor: '#7B5920', color: '#F3EFE6' }}
            >
              Shop Our Beans
              <span>→</span>
            </Link>
            <Link
              href="/wholesale"
              className="inline-flex items-center justify-center gap-3 w-full sm:w-auto px-8 md:px-10 py-4 rounded-full font-sans font-semibold text-sm tracking-widest uppercase border-2 transition-all duration-300 hover:scale-105"
              style={{ borderColor: '#7B5920', color: '#7B5920' }}
            >
              Wholesale Inquiry
            </Link>
          </div>
        </div>
      </section>
      </main>
      <Footer />
    </>
  );
}
